[package]
name = "trivial-fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive", "string"] }
libafl = "0.11.2"
libafl_bolts = "0.11.2"
libafl_qemu = { version = "0.11.2", features = ["usermode", "aarch64"] }
libc = "0.2.153"
log = "0.4.20"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"


[profile.release]
strip = true
