[package]
name = "trivial-fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive", "string"] }
libafl = "0.11.2"
libafl_bolts = "0.11.2"
libafl_qemu = { version = "0.11.2", features = ["usermode", "aarch64"] }
log = "0.4.20"
