name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/x86_64, linux/arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/twizmwazin/trivial-fuzzer-devcontainer
          cacheFrom: ghcr.io/twizmwazin/trivial-fuzzer-devcontainer
          push: never
          runCmd: cargo make all
          platform: ${{ matrix.platform }}
