name: Build

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  release:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: ["amd64", "aarch64"]
    container:
      image: rust
      options: --platform linux/${{ matrix.arch }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install cargo-make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential python3 python3-venv ninja-build libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo make release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: target/release/trivial-fuzzer-*
