name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [linux/x86_64, linux/arm64]
        runner: [ubuntu-latest, ubicloud-standard-2-arm]

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/twizmwazin/trivial-fuzzer-devcontainer
          cacheFrom: ghcr.io/twizmwazin/trivial-fuzzer-devcontainer
          push: never
          runCmd: cargo make all
