name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        runner:
          - arch: x86_64
            image: ubuntu-22.04
          - arch: aarch64
            image: ubicloud-standard-2-arm
          

    runs-on: ${{ matrix.runner.image }}

    steps:
      - name: Install dependenceies
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends python3-venv ninja-build llvm-18 clang-18
          rustup update
          cargo install cargo-make

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: cargo make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.runner.arch }}
          path: target/debug/trivial-fuzzer-*
