name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Make upload directory
        run: mkdir upload

      - name: Copy artifacts to upload dir
        run: |
          for f in $(ls artifact-x86_64); do
            cp artifact-x86_64/$f upload/$f.x86_64
          done
          for f in $(ls artifact-aarch64); do
            cp artifact-aarch64/$f upload/$f.aarch64
          done

      - name: Publish github release
        run: >
          gh release create
            ${{ github.ref_name }}
            --title "Trivial Fuzzer ${{ github.ref_name }}"
            --generate-notes
            upload/*

